root: true
env:
  es6: true
  node: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
  ecmaVersion: 2018
  sourceType: module
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
extends:
  - 'standard'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:prettier/recommended'
  - 'prettier/standard'
  - 'prettier/@typescript-eslint'
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': 'off'
